### ISSUE TITLE
Fatel Error and the PHP page hang

### ISSUE THREAD

**Issue by rkaartikeyan** [twilio/twilio-php#265] opened 2015-11-11 18:03 UTC
Hi,

i am getting following error and the page hanged, <code>Fatal error: Uncaught exception 'Services_Twilio_RestException' with message 'Permission to send an SMS has not been enabled for the region indicated by the 'To' number:</code>

**Comment by carlosdp** [comment] 2015-11-11 18:07
Hey @rkaartikeyan , that means the Twilio number you are using does not have the ability to send an SMS to that number. For a list of capabilities by country, you can look here https://www.twilio.com/help/faq/phone-numbers/which-countries-does-twilio-have-phone-numbers-in-and-what-are-their-capabilities . If that doesn't help, please reach out to our support team here https://www.twilio.com/help/contact and they can help you with buying a number that is capable of what you want it to do.

I'm going to close this issue as it has to do with Twilio numbers rather than the PHP library itself.

**Closed by carlosdp** 2015-11-11 18:07 UTC

**Comment by rkaartikeyan** [comment] 2015-11-11 18:11
If there is an Error, it should show the error, not make the site hanged. Due to the Fatal Error, my site is hanging. when i enable <code>error_reporting(-1);</code> in php, then only its showed this error. otherwise nothing a blank page and my site got hanged nothing load.

so how you are saying the problem is not PHP Library sir?

**Comment by carlosdp** [comment] 2015-11-11 18:18
Hey @rkaartikeyan, the Twilio library, like most libraries, will throw an exception when there is an error with your request. You need to "catch" the exceptions in order to prevent weird behavior such as a site hang. If your site is hanging, that is being caused by whatever PHP web framework you are using and how it handles uncaught exceptions.

If you need more guidance on how to handle errors such as these, I recommend reaching out on that web framework's issues/forums :smiley:

**Comment by rkaartikeyan** [comment] 2015-11-11 18:35
Hi, thanks for your kind replies, I didn't used any php frameworks, just i using Native PHP

this is my code:
```php
require('../sms/Twilio.php');
$to		= "+440000000"; //for Example
$body	= "Test"; 
$from	= $settings[22]; 
$sid	= $settings[20]; 
$tocken	= $settings[21]; 

$client = new Services_Twilio($sid, $tocken); 

$response = $client->account->messages->create(array( 
	'To'	=> $to, 
	'From'	=> $from, 
	'Body'	=> $body
));
print_r($response);
```

If there are no Error, everything works fine and i am getting Return array, but when there is a problem with mobile number, or with body message, its hanged. so how should i catch the error?

**Comment by rkaartikeyan** [comment] 2015-11-11 19:15
Thanks i have fixed with Try and Catch.

**Comment by hiteshkanwar** [comment] 2017-04-13 14:32
Please give permission to countries where you like to send sms/notification

https://www.twilio.com/console/sms/settings/geo-permissions
