### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by devil1629** [twilio/twilio-php#208] opened 2014-12-31 20:22 UTC
I m using this code to send a quick test sms.. and i m still getting this error. Any suggestions?

<?php

require('twilio-php/Services/Twilio.php');
if( $_SERVER['REQUEST_METHOD']== 'POST'){

$message = $_POST['message'];

$account_sid = 'ACfa5a532073c835aeb8b602a8cefa2076'; 
$auth_token = '{{ auth_token }}'; 
$client = new Services_Twilio($account_sid, $auth_token);

try{
$client->account->messages->create(array( 
'To' => "+***********", 
'From' => "+15168304525", 
'Body' => "hey")); }

catch(Exception $e){
    echo 'cauth exception'.$e->getMessage();
}
}
?>

**Comment by mrieck** [comment] 2015-01-02 16:12
I'm also getting this error in the latest build - but an older build still works with my code.  I'm going to revert back for now.

**Comment by skimbrel** [comment] 2015-01-02 16:35
Duplicate of https://github.com/twilio/twilio-php/issues/203; please see advice there for upgrading your system’s certificate bundles.

**Closed by skimbrel** 2015-01-02 16:35 UTC
