### ISSUE TITLE
RecordingList because the name is already in use

### ISSUE THREAD

**Issue by lucasdealmeida** [twilio/twilio-php#386] opened 2016-11-14 12:53 UTC
Hello, I getting this error "FatalErrorException in CallContext.php line 17 Cannot use Twilio\Rest\Api\V2010\Account\Call\RecordingList as RecordingList because the name is already in use" someone know how solve this error?

Thank you.

**Comment by ihumanable** [comment] 2016-11-30 12:11
Could you provide more context for how this error is occurring, we have an [Integration Test](https://github.com/twilio/twilio-php/blob/master/Twilio/Tests/Integration/Api/V2010/Account/CallTest.php) that uses CallContext and runs successfully.

**Comment by vadiml** [comment] 2016-12-20 16:02
Hi. Here is the sample code that produces the same error:

```
use Twilio\Rest\Client;

$client = new Client();

$recordings = $client->recordings->page();

foreach ($recordings as $recording) {
    $callSid = $recording->callSid;
    $client->calls($callSid)->fetch();
}
```

**Comment by joe248** [comment] 2017-01-16 22:39
I have this same issue.  Fetching a list of recordings with:

`$client->recordings->read()`

and then attempting to get the info on a call with:

`$client->calls($call_sid)->fetch();`

produces the error.

Not being able to get a call's info after fetching a list of recordings is a significant bug and is preventing me from moving forward with Twilio.  @vadiml provided documentation and a fix a month ago, which I can confirm fixed the issue.  Is this fix going to be implemented soon?

**Comment by adam1010** [comment] 2017-01-25 05:18
I'm experiencing the same issue with the newest PHP SDK. The patch from @vadiml on Dec 20 worked for me.

**Comment by dikirill** [comment] 2017-04-20 20:26
I have the same issue, and it reproducible under same conditions described by previous reporters.
I've sent this issue to the support, and hope soon we will see the solution.
It looks like issue is coming from the order we load dependencies, so if try for example run this command first:
`$client->calls($bogus_sid)->fetch();`
and after:
`$client->recordings->read();`
and now:
`$client->calls($call_sid)->fetch();`
No exception will be thrown.

For those who doesn't want to change source code, you can fetch bogus call details, and it will help for now.

**Comment by efossier** [comment] 2017-04-24 07:31
Thanks everyone we'll prioritize this for a fix.

**Comment by efossier** [comment] 2017-04-24 08:42
@dikirill @adam1010 @joe248 @vadiml 
I am unable to reproduce the issue with the latest php SDK (5.7.3). Here is the script I ran without error:
```php
<?php

require 'vendor/autoload.php';

use Twilio\Rest\Client;

$client = new Client("AC123", "AUTH_TOKEN");

print("Getting recordings\n");
$recordings = $client->recordings->read();

print("\nGetting calls\n");
$call = $client->calls("CA123")->fetch();

print("Gettings recordings for call");
$call_recordings = $call->recordings->read();
```

Are you all still seeing this error? If so can you try upgrading to the latest version of the library?

**Comment by dikirill** [comment] 2017-04-24 14:21
@efossier 
Yes, just upgraded to 5.7.3 and still have the error:

> Getting recordings
> 
> Getting calls
> 
> Fatal error: Cannot use Twilio\Rest\Api\V2010\Account\Call\RecordingList as RecordingList because the name is already in use in /test/vendor/twilio/sdk/Twilio/Rest/Api/V2010/Account/CallContext.php on line 17
> 
> Call Stack:
>     0.0002     351368   1. {main}() /test/test.php:0
>     0.2365    1946864   2. Twilio\Rest\Client->calls() /test/test.php:13
>     0.2365    1947240   3. Twilio\Rest\Client->__call() /test/test.php:13
>     0.2365    1947656   4. call_user_func_array:{/test/vendor/twilio/sdk/Twilio/Rest/Client.php:684}() /test/vendor/twilio/sdk/Twilio/Rest/Client.php:684
>     0.2365    1948048   5. Twilio\Rest\Client->contextCalls() /test/vendor/twilio/sdk/Twilio/Rest/Client.php:684
>     0.2365    1948048   6. Twilio\Rest\Api\V2010\AccountContext->calls() /test/vendor/twilio/sdk/Twilio/Rest/Client.php:348
>     0.2365    1948424   7. Twilio\Rest\Api\V2010\AccountContext->__call() /test/vendor/twilio/sdk/Twilio/Rest/Client.php:348
>     0.2369    1977480   8. call_user_func_array:{/test/vendor/twilio/sdk/Twilio/Rest/Api/V2010/AccountContext.php:570}() /test/vendor/twilio/sdk/Twilio/Rest/Api/V2010/AccountContext.php:570
>     0.2369    1977872   9. Twilio\Rest\Api\V2010\Account\CallList->getContext() /test/vendor/twilio/sdk/Twilio/Rest/Api/V2010/AccountContext.php:570
>     0.2369    1977872  10. spl_autoload_call() /test/vendor/twilio/sdk/Twilio/Rest/Api/V2010/Account/CallList.php:200
>     0.2369    1978032  11. Composer\Autoload\ClassLoader->loadClass() /test/vendor/twilio/sdk/Twilio/Rest/Api/V2010/Account/CallList.php:200
>     0.2369    1978144  12. Composer\Autoload\includeFile() /test/vendor/composer/ClassLoader.php:301

I'm running PHP 7.0.10

**Comment by efossier** [comment] 2017-04-24 15:06
@dikirill Interesting... I am running PHP 7.0.13 and can run the above script without problem. Im not a php expert by any means, is there any reason you can think of that we would be getting different results?

**Comment by efossier** [comment] 2017-04-24 15:31
@dikirill I downgraded to php 5.5 and am now seeing the error. We'll get a fix for this out soon.

**Comment by dikirill** [comment] 2017-04-24 18:29
@efossier Thank you!

**Comment by efossier** [comment] 2017-04-27 09:02
@dikirill After investigating this more it seems to be a systematic problem in how we are generating libraries for dynamic languages and it affects multiple other classes. We have this issue prioritized on our todo list however it may take a bit longer than anticipated to get a fix out.

**Comment by jmctwilio** [comment] 2017-08-07 20:50
@dikirill We've implemented a short-term fix for this Issue which should resolve the problem.  There is a more systemic issue of namespacing that will affect our libraries more generally.  We have that issue prioritized on our backlog.

**Closed by jmctwilio** 2017-08-07 20:50 UTC
Labels: Bug
