### ISSUE TITLE
Missing update parameter ip messaging next-gen

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#353] opened 2016-08-09 19:01 UTC
**Version:** 5.0.0-RC19
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

[This update method](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/IpMessaging/V1/CredentialContext.php#L62) is missing an optional update parameter `type`. It was there before the latest definition update as a mandatory parameter.

**Comment by ihumanable** [comment] 2016-08-09 20:05
Interesting, the api-definitions do not specify `type` as a valid argument for update, the proxy layer will not accept it either.  This might be a documentation error, or we need to update our proxy.

I will investigate further.

**Comment by mcelicalderon** [comment] 2016-08-09 20:23
Thanks! I got this from the [API docs](https://www.twilio.com/docs/api/ip-messaging/rest/credentials#action-update). We also have some snippets that update the `type` parameter. Didn't try to make an actual call to the API.

**Comment by ihumanable** [comment] 2016-08-09 20:25
I'm trying to find out internally what the intended behavior is, I'll have an update shortly.

**Comment by viktormuller** [comment] 2016-08-12 16:08
Type is not possible to update all other parameters are possible

**Comment by ihumanable** [comment] 2016-08-12 16:36
Our docs team will update the public documentation to remove this field from the Update properties.  Resolving as helper library is working correctly

**Closed by ihumanable** 2016-08-12 16:36 UTC
Labels: yoyodyne

**Comment by mcelicalderon** [comment] 2016-08-13 14:26
Great, thanks.
