### ISSUE TITLE
DeserializeException in Page.php line 43: Unable to fetch page

### ISSUE THREAD

**Issue by ashitvora** [twilio/twilio-php#374] opened 2016-09-12 06:02 UTC
While trying to get call logs, I get following error

```
DeserializeException in Page.php line 43:
Unable to fetch page
```

Here's my code.

```
class TwilioService {
	protected $twilio;
	protected $sid;
	protected $token;

	public function __construct($data) {
		$this->sid = $data['sid'];
		$this->token = $data['token'];
		$this->twilio = new Twilio($data['sid'], $data['token']);
	}

	public static function make($data) {
		return new static($data);
	}

	public function getCallLogs($start = null, $end = null) {
		// Loop over the list of calls and echo a property for each one
		foreach ($this->twilio->calls->read() as $call) {
			echo $call->direction;
		}
		die();
		$calls = $this->twilio->calls->read([]);

		return $calls;
	}
}
```

I did make sure SID and Token are not empty or null.

**Comment by ihumanable** [comment] 2016-09-14 05:47
That exception occurs when the read either returns a non-200 or the library detects an EOL condition.  The error message returned by the library is pretty poor, we recently upgraded most of the exceptions to be more informative, looks like this one got missed.

I will cut a new version as soon as possible (hopefully tomorrow) with better exception messages around this particular case (I will also try to reproduce locally).  I will update this issue once a version with more verbose error messages is available.  Once we have more information about this error we can provide more help in debugging this.

**Comment by ihumanable** [comment] 2016-09-14 19:31
Tentative PR is here https://github.com/twilio/twilio-php/pull/376 awaiting review

**Comment by ihumanable** [comment] 2016-09-15 22:05
@ashitvora twilio-php 5.4.0 has been released with more informative exceptions for this case.  Could you try updating?  The exception that will be thrown now is `Twilio\Exceptions\RestException` you can interrogate it with `getMessage()` `getCode()` and `getStatusCode()` to better understand why the paging is failing.

**Comment by ihumanable** [comment] 2016-10-09 03:41
Going to close this issue as inactive, please reopen if you are still having issues.

**Closed by ihumanable** 2016-10-09 03:41 UTC
Labels: More Info Needed

**Comment by jamesgraham** [comment] 2016-11-29 15:29
The error messaging still leaves a lot to be desired. I authenticated with invalid creds and got the lovely exception:

> [HTTP 401] Unable to fetch page: Authenticate

Digging deeper I discovered the actual exception is:
>  #content: "{"code": 20003, "detail": "Your AccountSid or AuthToken was incorrect.", "message": "Authenticate", "more_info": "https://www.twilio.com/docs/errors/20003", "status": 401}"
