### ISSUE TITLE
sms twilio with friendly name

### ISSUE THREAD

**Issue by keitaassane1** [twilio/twilio-php#671] opened 2020-11-21 12:57 UTC
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```php
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-php version: 
* php version:

**Comment by JenniferMah** [comment] 2020-11-23 22:50
@keitaassane1 

I'm going to close this issue since it doesn't look like there is any information in the issue template. If there is an issue you need addressed, please open another issue with the issue summary, steps to reproduce, code snippets, logs, or technical details information filled out.

**Closed by JenniferMah** 2020-11-23 22:50 UTC
